vim.cmd [[ colorscheme morning ]]
vim.cmd [[ highlight Normal guibg=None ]]
vim.cmd [[ highlight NonText guibg=None ]]
vim.cmd [[ highlight Normal ctermbg=None ]]
vim.cmd [[ highlight NonText ctermbg=None ]]
